import { CubeIcon } from '@sanity/icons'
import { defineField, defineType } from 'sanity'

export const thingType = defineType({
  name: 'thing',
  title: 'Thing',
  type: 'document',
  icon: CubeIcon,
  fields: [
    defineField({
      name: 'title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      type: 'text',
    }),
    defineField({
      name: 'featuredImage',
      title: 'Featured Image',
      type: 'image',
      options: {
        hotspot: true,
      },
      validation: (rule) => rule.required(),
      fields: [
        defineField({
          name: 'alt',
          type: 'string',
          title: 'Alt text',
        }),
        defineField({
          name: 'caption',
          type: 'string',
          title: 'Caption',
        }),
      ],
    }),
    defineField({
      name: 'featuredVideo',
      title: 'Featured Video (optional)',
      type: 'mux.video',
    }),
    defineField({
      name: 'images',
      title: 'Images',
      type: 'array',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            {
              name: 'alt',
              type: 'string',
              title: 'Alt text',
            },
            {
              name: 'caption',
              type: 'string',
              title: 'Caption',
              options: { isHighlighted: true },
            },
          ],
        },
      ],
      options: { layout: 'grid' },
    }),
    defineField({
      name: 'videos',
      title: 'Videos',
      type: 'array',
      options: { layout: 'grid' },
      of: [
        {
          type: 'object',
          name: 'videoItem',
          title: 'Video',
          fields: [
            defineField({
              name: 'file',
              title: 'Mux Video',
              type: 'mux.video',
              validation: (rule) => rule.required(),
            }),
            defineField({ name: 'title', type: 'string' }),
            defineField({ name: 'alt', title: 'Alt text', type: 'string' }),
            defineField({
              name: 'caption',
              type: 'string',
              options: { isHighlighted: true },
            }),
            defineField({
              name: 'poster',
              title: 'Poster image (optional)',
              type: 'image',
              options: { hotspot: true },
              fields: [{ name: 'alt', type: 'string', title: 'Alt text' }],
            }),
            defineField({
              name: 'autoplay',
              type: 'boolean',
              initialValue: false,
            }),
            defineField({ name: 'loop', type: 'boolean', initialValue: true }),
            defineField({ name: 'muted', type: 'boolean', initialValue: true }),
          ],
          preview: {
            select: {
              title: 'title',
              caption: 'caption',
              poster: 'poster',
            },
            prepare({ title, caption, poster }) {
              return {
                title: title || 'Video',
                subtitle: caption,
                media: poster,
              }
            },
          },
        },
      ],
    }),
    defineField({
      name: 'isAiGenerated',
      title: 'AI Generated',
      type: 'boolean',
      description: 'Is this content generated by artificial intelligence?',
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'featuredImage',
    },
  },
})
