import { CubeIcon } from '@sanity/icons'
import { defineField, defineType } from 'sanity'

export const thingType = defineType({
  name: 'thing',
  title: 'Thing',
  type: 'document',
  icon: CubeIcon,
  fields: [
    defineField({
      name: 'title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      type: 'text',
    }),
    defineField({
      name: 'image',
      type: 'image',
      options: {
        hotspot: true,
      },
      fields: [
        defineField({
          name: 'alt',
          type: 'string',
          title: 'Alt text',
        }),
        defineField({
          name: 'caption',
          type: 'string',
          title: 'Caption',
        }),
      ],
    }),
    defineField({
      name: 'video',
      title: 'Video',
      type: 'mux.video',
    }),
    defineField({
      name: 'isAiGenerated',
      title: 'AI Generated',
      type: 'boolean',
      description: 'Is this content generated by artificial intelligence?',
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'image',
    },
  },
})